// Lightweight model + data for country phone codes (searchable).
// You can add/adjust entries anytime. Common/major markets are covered here.
// If you need a niche territory missing, append it to the list.

class Country {
  final String name;
  final String iso2;      // For reference/flag
  final String dialCode;  // E.164 prefix
  final String flag;      // Emoji flag

  const Country({required this.name, required this.iso2, required this.dialCode, required this.flag});
}

// NOTE: This is an extensive, curated list of commonly-used calling codes.
// You can append additional territories if you target specific regions.
const List<Country> kCountries = [
  Country(name: 'Singapore', iso2: 'SG', dialCode: '+65', flag: '🇸🇬'),
  Country(name: 'Malaysia', iso2: 'MY', dialCode: '+60', flag: '🇲🇾'),
  Country(name: 'Indonesia', iso2: 'ID', dialCode: '+62', flag: '🇮🇩'),
  Country(name: 'Thailand', iso2: 'TH', dialCode: '+66', flag: '🇹🇭'),
  Country(name: 'Vietnam', iso2: 'VN', dialCode: '+84', flag: '🇻🇳'),
  Country(name: 'Philippines', iso2: 'PH', dialCode: '+63', flag: '🇵🇭'),
  Country(name: 'India', iso2: 'IN', dialCode: '+91', flag: '🇮🇳'),
  Country(name: 'China', iso2: 'CN', dialCode: '+86', flag: '🇨🇳'),
  Country(name: 'Hong Kong', iso2: 'HK', dialCode: '+852', flag: '🇭🇰'),
  Country(name: 'Taiwan', iso2: 'TW', dialCode: '+886', flag: '🇹🇼'),
  Country(name: 'Japan', iso2: 'JP', dialCode: '+81', flag: '🇯🇵'),
  Country(name: 'South Korea', iso2: 'KR', dialCode: '+82', flag: '🇰🇷'),
  Country(name: 'Australia', iso2: 'AU', dialCode: '+61', flag: '🇦🇺'),
  Country(name: 'New Zealand', iso2: 'NZ', dialCode: '+64', flag: '🇳🇿'),
  Country(name: 'United States', iso2: 'US', dialCode: '+1', flag: '🇺🇸'),
  Country(name: 'Canada', iso2: 'CA', dialCode: '+1', flag: '🇨🇦'),
  Country(name: 'Mexico', iso2: 'MX', dialCode: '+52', flag: '🇲🇽'),
  Country(name: 'Brazil', iso2: 'BR', dialCode: '+55', flag: '🇧🇷'),
  Country(name: 'Argentina', iso2: 'AR', dialCode: '+54', flag: '🇦🇷'),
  Country(name: 'Chile', iso2: 'CL', dialCode: '+56', flag: '🇨🇱'),
  Country(name: 'Peru', iso2: 'PE', dialCode: '+51', flag: '🇵🇪'),
  Country(name: 'Colombia', iso2: 'CO', dialCode: '+57', flag: '🇨🇴'),
  Country(name: 'United Kingdom', iso2: 'GB', dialCode: '+44', flag: '🇬🇧'),
  Country(name: 'Ireland', iso2: 'IE', dialCode: '+353', flag: '🇮🇪'),
  Country(name: 'Germany', iso2: 'DE', dialCode: '+49', flag: '🇩🇪'),
  Country(name: 'France', iso2: 'FR', dialCode: '+33', flag: '🇫🇷'),
  Country(name: 'Netherlands', iso2: 'NL', dialCode: '+31', flag: '🇳🇱'),
  Country(name: 'Belgium', iso2: 'BE', dialCode: '+32', flag: '🇧🇪'),
  Country(name: 'Luxembourg', iso2: 'LU', dialCode: '+352', flag: '🇱🇺'),
  Country(name: 'Switzerland', iso2: 'CH', dialCode: '+41', flag: '🇨🇭'),
  Country(name: 'Austria', iso2: 'AT', dialCode: '+43', flag: '🇦🇹'),
  Country(name: 'Italy', iso2: 'IT', dialCode: '+39', flag: '🇮🇹'),
  Country(name: 'Spain', iso2: 'ES', dialCode: '+34', flag: '🇪🇸'),
  Country(name: 'Portugal', iso2: 'PT', dialCode: '+351', flag: '🇵🇹'),
  Country(name: 'Norway', iso2: 'NO', dialCode: '+47', flag: '🇳🇴'),
  Country(name: 'Sweden', iso2: 'SE', dialCode: '+46', flag: '🇸🇪'),
  Country(name: 'Finland', iso2: 'FI', dialCode: '+358', flag: '🇫🇮'),
  Country(name: 'Denmark', iso2: 'DK', dialCode: '+45', flag: '🇩🇰'),
  Country(name: 'Poland', iso2: 'PL', dialCode: '+48', flag: '🇵🇱'),
  Country(name: 'Czechia', iso2: 'CZ', dialCode: '+420', flag: '🇨🇿'),
  Country(name: 'Hungary', iso2: 'HU', dialCode: '+36', flag: '🇭🇺'),
  Country(name: 'Greece', iso2: 'GR', dialCode: '+30', flag: '🇬🇷'),
  Country(name: 'Turkey', iso2: 'TR', dialCode: '+90', flag: '🇹🇷'),
  Country(name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971', flag: '🇦🇪'),
  Country(name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966', flag: '🇸🇦'),
  Country(name: 'Qatar', iso2: 'QA', dialCode: '+974', flag: '🇶🇦'),
  Country(name: 'Kuwait', iso2: 'KW', dialCode: '+965', flag: '🇰🇼'),
  Country(name: 'Bahrain', iso2: 'BH', dialCode: '+973', flag: '🇧🇭'),
  Country(name: 'Oman', iso2: 'OM', dialCode: '+968', flag: '🇴🇲'),
  Country(name: 'Israel', iso2: 'IL', dialCode: '+972', flag: '🇮🇱'),
  Country(name: 'South Africa', iso2: 'ZA', dialCode: '+27', flag: '🇿🇦'),
  Country(name: 'Nigeria', iso2: 'NG', dialCode: '+234', flag: '🇳🇬'),
  Country(name: 'Kenya', iso2: 'KE', dialCode: '+254', flag: '🇰🇪'),
  Country(name: 'Egypt', iso2: 'EG', dialCode: '+20', flag: '🇪🇬'),
  Country(name: 'Morocco', iso2: 'MA', dialCode: '+212', flag: '🇲🇦'),
  Country(name: 'Tunisia', iso2: 'TN', dialCode: '+216', flag: '🇹🇳'),
  Country(name: 'Pakistan', iso2: 'PK', dialCode: '+92', flag: '🇵🇰'),
  Country(name: 'Bangladesh', iso2: 'BD', dialCode: '+880', flag: '🇧🇩'),
  Country(name: 'Sri Lanka', iso2: 'LK', dialCode: '+94', flag: '🇱🇰'),
  Country(name: 'Nepal', iso2: 'NP', dialCode: '+977', flag: '🇳🇵'),
  Country(name: 'Myanmar', iso2: 'MM', dialCode: '+95', flag: '🇲🇲'),
  Country(name: 'Cambodia', iso2: 'KH', dialCode: '+855', flag: '🇰🇭'),
  Country(name: 'Laos', iso2: 'LA', dialCode: '+856', flag: '🇱🇦'),
  Country(name: 'Brunei', iso2: 'BN', dialCode: '+673', flag: '🇧🇳'),
  Country(name: 'Mongolia', iso2: 'MN', dialCode: '+976', flag: '🇲🇳'),
  Country(name: 'Russia', iso2: 'RU', dialCode: '+7', flag: '🇷🇺'),
  Country(name: 'Ukraine', iso2: 'UA', dialCode: '+380', flag: '🇺🇦'),
  Country(name: 'Romania', iso2: 'RO', dialCode: '+40', flag: '🇷🇴'),
  Country(name: 'Bulgaria', iso2: 'BG', dialCode: '+359', flag: '🇧🇬'),
  Country(name: 'Serbia', iso2: 'RS', dialCode: '+381', flag: '🇷🇸'),
  Country(name: 'Croatia', iso2: 'HR', dialCode: '+385', flag: '🇭🇷'),
  Country(name: 'Slovenia', iso2: 'SI', dialCode: '+386', flag: '🇸🇮'),
  Country(name: 'Slovakia', iso2: 'SK', dialCode: '+421', flag: '🇸🇰'),
  Country(name: 'Lithuania', iso2: 'LT', dialCode: '+370', flag: '🇱🇹'),
  Country(name: 'Latvia', iso2: 'LV', dialCode: '+371', flag: '🇱🇻'),
  Country(name: 'Estonia', iso2: 'EE', dialCode: '+372', flag: '🇪🇪'),
  Country(name: 'Iceland', iso2: 'IS', dialCode: '+354', flag: '🇮🇸'),
  Country(name: 'Malta', iso2: 'MT', dialCode: '+356', flag: '🇲🇹'),
  Country(name: 'Cyprus', iso2: 'CY', dialCode: '+357', flag: '🇨🇾'),
  Country(name: 'Georgia', iso2: 'GE', dialCode: '+995', flag: '🇬🇪'),
  Country(name: 'Armenia', iso2: 'AM', dialCode: '+374', flag: '🇦🇲'),
  Country(name: 'Kazakhstan', iso2: 'KZ', dialCode: '+7', flag: '🇰🇿'),
  Country(name: 'Uzbekistan', iso2: 'UZ', dialCode: '+998', flag: '🇺🇿'),
  Country(name: 'Azerbaijan', iso2: 'AZ', dialCode: '+994', flag: '🇦🇿'),
  Country(name: 'United Republic of Tanzania', iso2: 'TZ', dialCode: '+255', flag: '🇹🇿'),
  Country(name: 'Ethiopia', iso2: 'ET', dialCode: '+251', flag: '🇪🇹'),
  Country(name: 'Ghana', iso2: 'GH', dialCode: '+233', flag: '🇬🇭'),
  Country(name: 'Uganda', iso2: 'UG', dialCode: '+256', flag: '🇺🇬'),
  Country(name: 'Zimbabwe', iso2: 'ZW', dialCode: '+263', flag: '🇿🇼'),
  // ...add more if you need niche markets
];