// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9sCbH0hZRUO2wxk9IClyZC9DNcHCZBNY',
    appId: '1:648836412000:web:bd63d35e5459bd4eac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    authDomain: 'majurun-8d8b5.firebaseapp.com',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
    measurementId: 'G-SJNGLL06NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-glMd9_6VjXa50OG9jleoCkllNhtdFBY',
    appId: '1:648836412000:android:d6af7bffe4374005ac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2gckrxFr1bkoXQnf4gaaW-FE2HvDbwo',
    appId: '1:648836412000:ios:f473bb4ec42e8cd1ac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
    iosBundleId: 'com.example.majurun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2gckrxFr1bkoXQnf4gaaW-FE2HvDbwo',
    appId: '1:648836412000:ios:f473bb4ec42e8cd1ac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
    iosBundleId: 'com.example.majurun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9sCbH0hZRUO2wxk9IClyZC9DNcHCZBNY',
    appId: '1:648836412000:web:8282b88c16a6aa80ac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    authDomain: 'majurun-8d8b5.firebaseapp.com',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
    measurementId: 'G-P963LYWWNN',
  );
}
