/**
 * MajuRun — Seed Firestore with Sample Posts
 *
 * Reads asset_urls.json generated by upload_to_cloudinary.js,
 * then creates realistic seed posts in Firestore so the
 * social feed looks active for new users.
 *
 * SETUP:
 *   1. npm install firebase-admin dotenv
 *   2. Download Firebase service account key:
 *      Firebase Console → Project Settings → Service Accounts → Generate new private key
 *      Save as: scripts/firebase_service_account.json
 *   3. Run: node scripts/seed_firestore.js
 *
 * SAFE TO RE-RUN: checks for existing seed posts before inserting.
 */

const admin = require('firebase-admin');
const path  = require('path');
const fs    = require('fs');
require('dotenv').config({ path: path.join(__dirname, '.env') });

// ─── INIT FIREBASE ────────────────────────────────────────────────────────────

const serviceAccountPath = path.join(__dirname, 'firebase_service_account.json');
if (!fs.existsSync(serviceAccountPath)) {
  console.error('❌ Missing firebase_service_account.json');
  console.error('   Download from: Firebase Console → Project Settings → Service Accounts');
  process.exit(1);
}

admin.initializeApp({
  credential: admin.credential.cert(require(serviceAccountPath)),
});

const db = admin.firestore();

// ─── LOAD ASSET URLS ─────────────────────────────────────────────────────────

const urlsPath = path.join(__dirname, 'output', 'asset_urls.json');
let assetUrls = {};
if (fs.existsSync(urlsPath)) {
  assetUrls = JSON.parse(fs.readFileSync(urlsPath, 'utf8'));
  console.log(`📦 Loaded ${Object.keys(assetUrls).length} asset URLs`);
} else {
  console.warn('⚠️  No asset_urls.json found — using placeholder URLs');
  console.warn('   Run upload_to_cloudinary.js first for real URLs');
}

function getUrl(key) {
  return assetUrls[key] || `https://placeholder.com/${key}`;
}

// ─── SEED POST DEFINITIONS ───────────────────────────────────────────────────

// Spread posts over past 30 days so feed looks organic
function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return admin.firestore.Timestamp.fromDate(d);
}

const SEED_POSTS = [
  // ── MOTIVATIONAL QUOTES ──
  {
    content: "Every kilometre is a choice. Choose to keep going. 💪",
    mapImageUrl: getUrl('seed_posts/seed_motivation_1.jpg'),
    likeCount: 142,
    commentCount: 18,
    createdAt: daysAgo(1),
    tags: ['motivation'],
  },
  {
    content: "Your only competition is yesterday's version of you. 🏃",
    mapImageUrl: getUrl('seed_posts/seed_motivation_2.jpg'),
    likeCount: 98,
    commentCount: 11,
    createdAt: daysAgo(2),
    tags: ['motivation'],
  },
  {
    content: "The run you almost didn't do is always the best one. 🌅",
    mapImageUrl: getUrl('seed_posts/seed_motivation_3.jpg'),
    likeCount: 213,
    commentCount: 27,
    createdAt: daysAgo(3),
    tags: ['motivation'],
  },
  {
    content: "Slow miles are still miles. Every step counts. 🐢",
    mapImageUrl: getUrl('seed_posts/seed_motivation_4.jpg'),
    likeCount: 176,
    commentCount: 22,
    createdAt: daysAgo(4),
    tags: ['motivation'],
  },
  {
    content: "Don't stop when you're tired. Stop when you're done. 🔥",
    mapImageUrl: getUrl('seed_posts/seed_motivation_5.jpg'),
    likeCount: 289,
    commentCount: 34,
    createdAt: daysAgo(5),
    tags: ['motivation'],
  },
  {
    content: "Lace up. Show up. Level up. Every single day. 👟",
    mapImageUrl: getUrl('seed_posts/seed_motivation_6.jpg'),
    likeCount: 156,
    commentCount: 19,
    createdAt: daysAgo(6),
    tags: ['motivation'],
  },
  {
    content: "One more kilometre always sounds impossible until it's done. 💫",
    mapImageUrl: getUrl('seed_posts/seed_motivation_7.jpg'),
    likeCount: 201,
    commentCount: 25,
    createdAt: daysAgo(7),
    tags: ['motivation'],
  },
  {
    content: "Rain doesn't cancel runs. It just makes the story better. 🌧️",
    mapImageUrl: getUrl('seed_posts/seed_motivation_8.jpg'),
    likeCount: 324,
    commentCount: 41,
    createdAt: daysAgo(8),
    tags: ['motivation', 'weather'],
  },

  // ── ACHIEVEMENT ANNOUNCEMENTS ──
  {
    content: "Just ran my first 5K! 🎉 Never thought I'd say that. The journey begins here!",
    mapImageUrl: getUrl('seed_posts/seed_achievement_5k.jpg'),
    distance: '5.0',
    pace: '6:24',
    bpm: 158,
    planTitle: '5K Beginner Plan',
    likeCount: 445,
    commentCount: 67,
    createdAt: daysAgo(9),
    tags: ['achievement', '5k', 'firstrun'],
  },
  {
    content: "10K DONE! Never thought I'd say that 6 weeks ago. Training works! 💪",
    mapImageUrl: getUrl('seed_posts/seed_achievement_10k.jpg'),
    distance: '10.1',
    pace: '5:58',
    bpm: 165,
    planTitle: '10K Training Plan',
    likeCount: 512,
    commentCount: 78,
    createdAt: daysAgo(11),
    tags: ['achievement', '10k'],
  },
  {
    content: "7-day streak unlocked! Consistency is everything. Don't break the chain. 🔥",
    mapImageUrl: getUrl('seed_posts/seed_achievement_streak.jpg'),
    likeCount: 387,
    commentCount: 52,
    createdAt: daysAgo(13),
    tags: ['streak', 'achievement'],
  },
  {
    content: "New personal best! 4:32/km 🤯 I genuinely didn't think I had that in me!",
    mapImageUrl: getUrl('seed_posts/seed_achievement_pb.jpg'),
    distance: '5.2',
    pace: '4:32',
    bpm: 178,
    planTitle: 'Speed Training',
    likeCount: 621,
    commentCount: 89,
    createdAt: daysAgo(15),
    tags: ['personalbest', 'achievement'],
  },

  // ── COMMUNITY / LIFESTYLE ──
  {
    content: "Running alone is great. Running with your crew is better. Saturday morning energy! 👟",
    mapImageUrl: getUrl('seed_posts/seed_community_group.jpg'),
    likeCount: 298,
    commentCount: 43,
    createdAt: daysAgo(17),
    tags: ['community', 'grouprun'],
  },
  {
    content: "Saturday morning parkrun energy is unmatched. See you all next week! 🌅",
    mapImageUrl: getUrl('seed_posts/seed_community_parkrun.jpg'),
    likeCount: 267,
    commentCount: 38,
    createdAt: daysAgo(19),
    tags: ['parkrun', 'community'],
  },
  {
    content: "Found my happy place. 🌲 Trail running hits completely different. Zero regrets.",
    mapImageUrl: getUrl('seed_posts/seed_community_trail.jpg'),
    likeCount: 445,
    commentCount: 61,
    createdAt: daysAgo(21),
    tags: ['trail', 'nature'],
  },
  {
    content: "Earned this. ☕ Post-run coffee is genuinely the best coffee in existence.",
    mapImageUrl: getUrl('seed_posts/seed_lifestyle_coffee.jpg'),
    likeCount: 534,
    commentCount: 72,
    createdAt: daysAgo(23),
    tags: ['lifestyle', 'recovery'],
  },
  {
    content: "Rest days are part of the plan. Listen to your body — it knows. 🧘",
    mapImageUrl: getUrl('seed_posts/seed_lifestyle_recovery.jpg'),
    likeCount: 312,
    commentCount: 47,
    createdAt: daysAgo(25),
    tags: ['recovery', 'wellness'],
  },

  // ── TRAINING TIPS ──
  {
    content: "Pro tip: Never skip your warm-up. 5 minutes now saves 5 weeks of injury. Trust me on this one. 🔥",
    mapImageUrl: getUrl('seed_posts/seed_tip_warmup.jpg'),
    likeCount: 489,
    commentCount: 63,
    createdAt: daysAgo(27),
    tags: ['tip', 'training'],
  },
  {
    content: "Drink before you're thirsty. By the time you feel thirst you're already dehydrated. Stay ahead of it. 💧",
    mapImageUrl: getUrl('seed_posts/seed_tip_hydration.jpg'),
    likeCount: 356,
    commentCount: 44,
    createdAt: daysAgo(29),
    tags: ['tip', 'hydration'],
  },
  {
    content: "Easy runs should feel EASY. If you can't hold a conversation, slow down. Most people run their easy runs way too fast. 🗣️",
    mapImageUrl: getUrl('seed_posts/seed_tip_pace.jpg'),
    likeCount: 412,
    commentCount: 58,
    createdAt: daysAgo(30),
    tags: ['tip', 'pacing'],
  },
];

// ─── MAIN ────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🌱 MajuRun Firestore Seeder\n');

  // Check if seed posts already exist
  const existing = await db.collection('posts')
    .where('userId', '==', 'seed_account')
    .limit(1)
    .get();

  if (!existing.empty) {
    console.log('⚠️  Seed posts already exist in Firestore.');
    console.log('   Delete existing seed posts first or run with --force flag.');
    const force = process.argv.includes('--force');
    if (!force) {
      console.log('\n   To re-seed: node scripts/seed_firestore.js --force');
      process.exit(0);
    }
    console.log('   --force flag detected, deleting existing seed posts...\n');
    const allSeed = await db.collection('posts').where('userId', '==', 'seed_account').get();
    const batch = db.batch();
    allSeed.docs.forEach(doc => batch.delete(doc.ref));
    await batch.commit();
    console.log(`   Deleted ${allSeed.size} existing seed posts\n`);
  }

  console.log(`📝 Creating ${SEED_POSTS.length} seed posts...\n`);

  const batch = db.batch();
  let count = 0;

  for (const post of SEED_POSTS) {
    const ref = db.collection('posts').doc();
    batch.set(ref, {
      userId: 'seed_account',
      username: 'MajuRun Community',
      userAvatar: getUrl('mascot/mascot_running.png'),
      type: 'seed_post',
      isSeed: true,
      content: post.content,
      mapImageUrl: post.mapImageUrl,
      distance: post.distance ?? null,
      pace: post.pace ?? null,
      bpm: post.bpm ?? null,
      planTitle: post.planTitle ?? null,
      likes: [],
      likeCount: post.likeCount,
      commentCount: post.commentCount,
      tags: post.tags ?? [],
      createdAt: post.createdAt,
    });
    console.log(`  ✅ "${post.content.substring(0, 50)}..."`);
    count++;
  }

  await batch.commit();

  console.log(`\n─────────────────────────────────`);
  console.log(`✅ Created ${count} seed posts in Firestore`);
  console.log(`─────────────────────────────────`);
  console.log('\n✨ Done! Open the app and check the social feed.');
  process.exit(0);
}

main().catch(err => {
  console.error('💥 Fatal error:', err);
  process.exit(1);
});
