import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:majurun/modules/home/domain/entities/post.dart';
import 'package:majurun/modules/home/data/repositories/post_repository_impl.dart';
import 'quoted_post_preview.dart';
import 'comment_sheet.dart';
import 'run_map_preview.dart';
import 'package:timeago/timeago.dart' as timeago;

class PostCard extends StatelessWidget {
  final AppPost post;
  const PostCard({super.key, required this.post});

  bool _isSessionPost(AppPost post) {
    final text = post.content.toLowerCase();
    // Training posts generated by your ActiveWorkoutScreen include these phrases
    return text.contains('training session') || text.contains('completed week');
  }

  @override
  Widget build(BuildContext context) {
    final repo = PostRepositoryImpl();
    final currentUser = FirebaseAuth.instance.currentUser;
    final currentUserId = currentUser?.uid ?? "";
    final isOwnPost = currentUserId.isNotEmpty && post.userId == currentUserId;
    final isLiked = post.likes.contains(currentUserId);

    final isRepost = post.quotedPostId != null &&
        post.quotedPostId!.isNotEmpty &&
        post.content.trim().isEmpty;

    final isSession = _isSessionPost(post);

    return Container(
      width: double.infinity,
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      padding: const EdgeInsets.symmetric(vertical: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          )
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const CircleAvatar(
                  backgroundColor: Colors.blueGrey,
                  radius: 18,
                  child: Icon(Icons.person, color: Colors.white, size: 20),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Flexible(
                            child: Text(
                              post.username,
                              style: const TextStyle(fontWeight: FontWeight.bold),
                              overflow: TextOverflow.ellipsis,
                              maxLines: 1,
                            ),
                          ),
                          if (isRepost) ...[
                            const SizedBox(width: 6),
                            const Icon(Icons.repeat_rounded, size: 16, color: Colors.green),
                            const SizedBox(width: 4),
                            Text(
                              "reposted",
                              style: TextStyle(color: Colors.grey[600], fontSize: 13),
                            ),
                          ],
                          // ✅ SESSION badge for training posts (UI only, safe)
                          if (isSession) ...[
                            const SizedBox(width: 8),
                            _pill("SESSION", Icons.fitness_center, Colors.green),
                          ],
                        ],
                      ),
                      Text(
                        timeago.format(post.createdAt),
                        style: TextStyle(color: Colors.grey[600], fontSize: 12),
                      ),
                    ],
                  ),
                ),
                if (isOwnPost)
                  IconButton(
                    icon: const Icon(Icons.delete_forever, color: Colors.redAccent, size: 24),
                    onPressed: () async {
                      final confirm = await _showDeleteDialog(context);
                      if (confirm == true) {
                        await repo.deletePost(post.id);
                      }
                    },
                  ),
              ],
            ),
          ),

          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Text Content
                if (post.content.trim().isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8.0),
                    child: Text(
                      post.content,
                      style: const TextStyle(fontSize: 15, height: 1.4),
                    ),
                  ),

                // ✅ Media first: so training plan images show even without GPS route
                _buildMediaSection(post),

                // Route preview (GPS Path) if available
                if (post.routePoints != null && post.routePoints!.isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.only(top: 10),
                    child: RunMapPreview(points: post.routePoints!),
                  ),

                // Quoted Post / Repost Preview
                if (post.quotedPostId != null && post.quotedPostId!.isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.only(top: 10),
                    child: QuotedPostPreview(postId: post.quotedPostId!),
                  ),

                // ✅ If neither media nor routePoints exist, show a clean placeholder
                if (post.media.isEmpty && (post.routePoints == null || post.routePoints!.isEmpty))
                  Padding(
                    padding: const EdgeInsets.only(top: 10),
                    child: _emptyPreview(),
                  ),

                const Divider(height: 32),

                // Interaction Buttons
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    _ActionButton(
                      icon: isLiked ? Icons.favorite : Icons.favorite_border,
                      label: '${post.likes.length}',
                      color: isLiked ? Colors.red : Colors.grey[600],
                      onTap: currentUserId.isNotEmpty
                          ? () => repo.toggleLike(post.id, currentUserId)
                          : null,
                    ),
                    _ActionButton(
                      icon: Icons.chat_bubble_outline,
                      label: 'Comment',
                      onTap: () => showModalBottomSheet(
                        context: context,
                        isScrollControlled: true,
                        backgroundColor: Colors.transparent,
                        builder: (_) => CommentSheet(postId: post.id),
                      ),
                    ),
                    _ActionButton(
                      icon: Icons.repeat_rounded,
                      label: 'Repost',
                      onTap: currentUserId.isNotEmpty
                          ? () {
                              final username = currentUser?.displayName ?? "Runner";
                              repo.repost(post, currentUserId, username);
                            }
                          : null,
                    ),
                  ],
                ),
                const SizedBox(height: 8),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ✅ Modern pill badge
  Widget _pill(String text, IconData icon, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withValues(alpha: 0.25)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 14, color: color),
          const SizedBox(width: 6),
          Text(
            text,
            style: TextStyle(fontSize: 11, fontWeight: FontWeight.w700, color: color),
          ),
        ],
      ),
    );
  }

  Widget _emptyPreview() {
    return Container(
      height: 160,
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.grey.shade100,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.image_outlined, size: 34, color: Colors.grey.shade400),
            const SizedBox(height: 8),
            Text(
              "No preview available",
              style: TextStyle(color: Colors.grey.shade500, fontSize: 12, fontWeight: FontWeight.w600),
            ),
          ],
        ),
      ),
    );
  }

  Future<bool?> _showDeleteDialog(BuildContext context) {
    return showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text("Delete Post?"),
        content: const Text("This will permanently remove this post."),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text("Cancel"),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text("Delete", style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );
  }

  Widget _buildMediaSection(AppPost post) {
    if (post.media.isEmpty) return const SizedBox.shrink();

    // Keep your existing behavior: show first media image (image/video preview can be extended later)
    return Padding(
      padding: const EdgeInsets.only(top: 10),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: Image.network(
          post.media.first.url,
          fit: BoxFit.cover,
          width: double.infinity,
          height: 220,
          errorBuilder: (context, error, stackTrace) {
            return Container(
              height: 220,
              color: Colors.grey.shade200,
              child: const Center(
                child: Icon(Icons.broken_image, size: 60, color: Colors.grey),
              ),
            );
          },
        ),
      ),
    );
  }
}

class _ActionButton extends StatelessWidget {
  final IconData icon;
  final String label;
  final VoidCallback? onTap;
  final Color? color;

  const _ActionButton({
    required this.icon,
    required this.label,
    required this.onTap,
    this.color,
  });

  @override
  Widget build(BuildContext context) {
    final isEnabled = onTap != null;
    return InkWell(
      onTap: isEnabled ? onTap : null,
      borderRadius: BorderRadius.circular(8),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 12),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              icon,
              size: 18,
              color: isEnabled ? (color ?? Colors.grey[700]) : Colors.grey[400],
            ),
            const SizedBox(width: 4),
            Text(
              label,
              style: TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w600,
                color: isEnabled ? (color ?? Colors.grey[700]) : Colors.grey[400],
              ),
            ),
          ],
        ),
      ),
    );
  }
}