// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYoNsfBq9uY28Jxg8q9hBLtdcUureKQo',
    appId: '1:852818479467:web:5304d5106a881d63eee42e',
    messagingSenderId: '852818479467',
    projectId: 'majurun-dev',
    authDomain: 'majurun-dev.firebaseapp.com',
    storageBucket: 'majurun-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoS3MRLegGHyTxcrZmQj4Fhwz3y6Ymh8E',
    appId: '1:852818479467:android:47186545243005b7eee42e',
    messagingSenderId: '852818479467',
    projectId: 'majurun-dev',
    storageBucket: 'majurun-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01SY-dxgeyeJ_iWrJtdJOILHozPrhgdE',
    appId: '1:852818479467:ios:8cb3a476f462713ceee42e',
    messagingSenderId: '852818479467',
    projectId: 'majurun-dev',
    storageBucket: 'majurun-dev.firebasestorage.app',
    iosBundleId: 'com.majurun.app',
  );
}
