// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWkbogBZ5sLctxyibzT7Hcsnv3B2XY9_E',
    appId: '1:648836412000:web:bd63d35e5459bd4eac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    authDomain: 'majurun-8d8b5.firebaseapp.com',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
    measurementId: 'G-SJNGLL06NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVMfuJWtuUeyiW69OZr-qlySyCgk23-vk',
    appId: '1:648836412000:android:015b64300bfff880ac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2gckrxFr1bkoXQnf4gaaW-FE2HvDbwo',
    appId: '1:648836412000:ios:29f733f7a3e51021ac8905',
    messagingSenderId: '648836412000',
    projectId: 'majurun-8d8b5',
    storageBucket: 'majurun-8d8b5.firebasestorage.app',
    androidClientId: '648836412000-7mnmjnufeocef13f014tmv41jfjap691.apps.googleusercontent.com',
    iosClientId: '648836412000-iustsqi2f7i95liauoe6dbaqrj4kc0pg.apps.googleusercontent.com',
    iosBundleId: 'com.majurun.app',
  );
}
