// AUTO-GENERATED by scripts/upload_to_cloudinary.js
// Run that script after uploading assets to Cloudinary to regenerate with real URLs.
// Placeholder URLs below — replace by running the upload script.

class AssetUrls {
  AssetUrls._();

  // ─── BADGES ───
  static const String badge5k = '';
  static const String badge10k = '';
  static const String badge21k = '';
  static const String badge42k = '';
  static const String badgeStreak7 = '';
  static const String badgeStreak30 = '';
  static const String badgeStreak100 = '';
  static const String badgeStreak365 = '';
  static const String badgeFirstRun = '';
  static const String badgeSpeedDemon = '';
  static const String badgeEarlyBird = '';
  static const String badgeNightOwl = '';
  static const String badgeRainRunner = '';
  static const String badgeCommunity = '';

  // ─── ANIMATED BADGES (GIF) ───
  static const String badge5kAnimated = '';
  static const String badgeStreakAnimated = '';
  static const String badgeUnlockAnimated = '';

  // ─── RUN CELEBRATIONS ───
  static const String celebrationShortRun = '';
  static const String celebration5k = '';
  static const String celebration10k = '';
  static const String celebrationHalfMarathon = '';
  static const String celebrationMarathon = '';
  static const String celebrationPersonalBest = '';

  // ─── CELEBRATION VIDEOS ───
  static const String videoCelebrationShort = '';
  static const String videoCelebration5k = '';
  static const String videoCelebration10k = '';
  static const String videoCelebrationHalf = '';
  static const String videoCelebrationMarathon = '';
  static const String videoCelebrationPb = '';

  // ─── TRAINING PLAN COVERS ───
  static const String planCoverBeginner = '';
  static const String planCover5k = '';
  static const String planCover10k = '';
  static const String planCoverHalfMarathon = '';
  static const String planCoverMarathon = '';
  static const String planCoverWeightLoss = '';
  static const String planCoverSpeed = '';
  static const String planCoverTrail = '';

  // ─── ONBOARDING ───
  static const String onboardingWelcome = '';
  static const String onboardingTrack = '';
  static const String onboardingCommunity = '';
  static const String onboardingGoals = '';

  // ─── ONBOARDING VIDEOS ───
  static const String videoOnboarding1 = '';
  static const String videoOnboarding2 = '';
  static const String videoOnboarding3 = '';
  static const String videoOnboarding4 = '';

  // ─── EMPTY STATES ───
  static const String emptyNoRuns = '';
  static const String emptyNoFollowers = '';
  static const String emptyNoPosts = '';
  static const String emptyNoAchievements = '';

  // ─── MASCOT ───
  static const String mascotRunning = '';
  static const String mascotCelebrating = '';
  static const String mascotTired = '';
  static const String mascotCoaching = '';
  static const String mascotWaving = '';
  static const String mascotThinking = '';

  // ─── FEED BACKGROUND VIDEOS ───
  static const String videoBgDawnRun = '';
  static const String videoBgCityNight = '';
  static const String videoBgTrailForest = '';
  static const String videoBgRainRun = '';
  static const String videoBgTrack = '';

  // ─── STREAK MILESTONE VIDEOS ───
  static const String videoStreak7 = '';
  static const String videoStreak30 = '';
  static const String videoStreak100 = '';

  // ─── BADGE UNLOCK VIDEOS ───
  static const String videoBadgeUnlock5k = '';
  static const String videoBadgeUnlockStreak = '';
  static const String videoBadgeUnlockGeneric = '';

  // ─── SPLASH SCREEN ───
  static const String videoSplash = '';
  static const String videoSplashRunner = '';

  /// Returns the correct celebration asset URL based on distance in km.
  /// Returns video URL if available, falls back to image.
  static String celebrationForDistance(double distanceKm, {bool video = false}) {
    if (video) {
      if (distanceKm >= 42.195) return videoCelebrationMarathon;
      if (distanceKm >= 21.0975) return videoCelebrationHalf;
      if (distanceKm >= 10.0) return videoCelebration10k;
      if (distanceKm >= 5.0) return videoCelebration5k;
      return videoCelebrationShort;
    }
    if (distanceKm >= 42.195) return celebrationMarathon;
    if (distanceKm >= 21.0975) return celebrationHalfMarathon;
    if (distanceKm >= 10.0) return celebration10k;
    if (distanceKm >= 5.0) return celebration5k;
    return celebrationShortRun;
  }

  /// Returns badge URL for a given badge name (matches UserStatsService badge names).
  static String badgeForName(String badgeName) {
    switch (badgeName) {
      case '5K':           return badge5k;
      case '10K':          return badge10k;
      case 'Half Marathon': return badge21k;
      case 'Marathon':     return badge42k;
      default:             return badgeUnlockAnimated;
    }
  }

  /// Returns streak badge URL based on streak count.
  static String badgeForStreak(int streakDays) {
    if (streakDays >= 365) return badgeStreak365;
    if (streakDays >= 100) return badgeStreak100;
    if (streakDays >= 30)  return badgeStreak30;
    if (streakDays >= 7)   return badgeStreak7;
    return '';
  }
}
